'addde comments'

diff --git a/.github/scripts/tag_deployment b/.github/scripts/tag_deployment
--- a/.github/scripts/tag_deployment
+++ b/.github/scripts/tag_deployment
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+# exit when any command fails
+set -e
+
 echo "Writing Release Version to plant-simulator-deployment"
 echo "--------------------------------"
 echo "GH_REPO              = $GH_REPO"
