added te

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -38,16 +38,20 @@ jobs:
   - stage: docker_push
     script: 
       - sbt "set test in assembly := {}" assembly
-      - if ! sh docker/docker_travis.sh; then
-        echo "Error setting up Docker Registry credentials.... EXITING" >&2
+      #- if ! sh docker/docker_travis.sh; then
+        #echo "Error setting up Docker Registry credentials.... EXITING" >&2
 
-        elif ! sh docker/docker_push.sh; then
-        echo "Error pushing Docker image into Docker hub.... EXITING" >&2
+        #elif ! sh docker/docker_push.sh; then
+        #echo "Error pushing Docker image into Docker hub.... EXITING" >&2
 
-        elif ! sh scripts/after_success_check.sh; then
-        echo "Error running liv_query.sh; rest of script cancelled." >&2
+        #elif ! sh scripts/after_success_check.sh; then
+        #echo "Error running liv_query.sh; rest of script cancelled." >&2
 
-        fi
+        #fi
+      - sh docker/docker_travis.sh && echo "Success setting up Docker Registry credentials" && \
+        sh docker/docker_push.sh && echo "Success pushing Docker image into Docker hub" && \
+        sh scripts/after_success_check.sh && echo "Success writing tag to plant-simulator-deployment" && \
+
       #- bash docker/docker_travis.sh
       #- bash docker/docker_push.sh
       # Write the Docker tag version into the plant-simulator-deployment project
