addd scrip

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -14,7 +14,6 @@ env:
   - PLANT_SIMULATOR_DEPLOYMENT_REPO_NAME=plant-simulator-deployment
 # Script to skip CI builds when non-essential files are commited (like README.md)
 before_install:
-  - bash docker/docker_travis.sh
   - bash scripts/before_install_check.sh
 before_cache:
 - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
@@ -39,9 +38,20 @@ jobs:
   - stage: docker_push
     script: 
       - sbt "set test in assembly := {}" assembly
-      - bash docker/docker_push.sh
+      - if ! bash docker/docker_travis.sh; then
+        echo "Error setting up Docker Registry credentials.... EXITING" >&2
+
+        elif ! bash docker/docker_push.sh; then
+        echo "Error pushing Docker image into Docker hub.... EXITING" >&2
+
+        elif ! bash scripts/after_success_check.sh; then
+        echo "Error running liv_query.sh; rest of script cancelled." >&2
+
+        fi
+      #- bash docker/docker_travis.sh
+      #- bash docker/docker_push.sh
       # Write the Docker tag version into the plant-simulator-deployment project
-      - bash scripts/after_success_check.sh
+      #- bash scripts/after_success_check.sh
     if: tag IS present
 after_script:
   - echo $TRAVIS_BRANCH
